version: "3.8"

services:
  equity-analyzer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./data:/app/data # Optional: for persistent data storage
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a data service for persistent storage
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
# volumes:
#   redis_data:
